In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(0)

array([], dtype=float64)

In [103]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
# Just use 
np.zeros(3,dtype=int)

array([0, 0, 0])

Docstring:

zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

In [13]:
x = np.ones([4,4])

In [14]:
y = np.ones((4,4))

In [16]:
type(x) == type(y)

True

In [101]:

newlin = np.linspace(0,10,5,retstep=True)
newlin

(array([  0. ,   2.5,   5. ,   7.5,  10. ]), 2.5)

In [102]:
newlin[1]

2.5

In [23]:
# identity matrix 
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
#random number
np.random.rand(5)

array([ 0.79932704,  0.56459647,  0.76079914,  0.73730285,  0.3771098 ])

In [27]:
np.random.rand(5,5)

array([[ 0.67206916,  0.13417383,  0.70942561,  0.3402131 ,  0.43326174],
       [ 0.70337103,  0.5308001 ,  0.38755274,  0.82602154,  0.93881783],
       [ 0.4940392 ,  0.09279649,  0.0868594 ,  0.90731219,  0.5375248 ],
       [ 0.70475286,  0.6382928 ,  0.92783908,  0.32829083,  0.95720733],
       [ 0.08775546,  0.01511936,  0.67439796,  0.20197844,  0.11194651]])

In [30]:
np.random.randn(2,2)

array([[ 0.45670704,  1.53425803],
       [ 0.62353497,  0.70034307]])

In [31]:
np.random.randint(1,100)

39

In [32]:
np.random.randint(1,100,10)

array([19, 72, 69, 61, 39, 18, 85, 88, 73, 86])

In [33]:
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr= np.random.randint(0,50,10)

In [36]:
ranarr

array([25, 13, 12, 24, 19, 25, 20, 14, 40, 24])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
# elements should be same 
arr.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [40]:
ranarr.max()

40

In [41]:
ranarr.min()

12

In [42]:
#Index location
ranarr.argmax()

8

In [44]:
arr.shape


(25,)

In [45]:
ranarr.shape


(10,)

In [46]:
arr.dtype

dtype('int64')

In [47]:
arr[8]

8

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [52]:
arr[:3]

array([0, 1, 2])

In [53]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [67]:
arr[::-1]

array([ 24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,
        11,  10,   9,   8,   7,   6,   5, 100, 100, 100, 100, 100])

In [68]:
arr[0:5] = 100

In [69]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [70]:
arr_copy = arr.copy()

In [71]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [73]:
arr[::-1]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [85]:
arr_2d = np.random.rand(5,5)

In [86]:
arr_2d

array([[ 0.55788866,  0.50183254,  0.62327018,  0.85884198,  0.22237589],
       [ 0.50664137,  0.34809989,  0.36900775,  0.09654541,  0.54265583],
       [ 0.81940556,  0.24181912,  0.6222243 ,  0.12129691,  0.27155592],
       [ 0.8834046 ,  0.74832289,  0.24179721,  0.74470464,  0.21960505],
       [ 0.07734022,  0.4197679 ,  0.79187501,  0.34918106,  0.36668914]])

In [87]:
arr_2d[1,2]

0.36900775457423929

In [89]:
arr_2d[1][2]

0.36900775457423929

In [92]:
arr_2d[:3,1:]

array([[ 0.50183254,  0.62327018,  0.85884198,  0.22237589],
       [ 0.34809989,  0.36900775,  0.09654541,  0.54265583],
       [ 0.24181912,  0.6222243 ,  0.12129691,  0.27155592]])

In [95]:
arr_2d[arr_2d < 0.5]

array([ 0.22237589,  0.34809989,  0.36900775,  0.09654541,  0.24181912,
        0.12129691,  0.27155592,  0.24179721,  0.21960505,  0.07734022,
        0.4197679 ,  0.34918106,  0.36668914])

In [96]:
array_2d = np.arange(50).reshape(5,10)

In [97]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [98]:
array_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [99]:
array_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])