<h1>Broadcasting</h1>

In [2]:
import numpy as np

In [4]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [6]:
# shape
my_3D_array.shape

(2, 7, 5)

In [10]:
# number of dimensions
my_3D_array.ndim

3

In [8]:
# size; number of elements
my_3D_array.size

70

In [9]:
# data type for each element
my_3D_array.dtype

dtype('int64')

In [12]:
5 * my_3D_array

array([[[  0,   5,  10,  15,  20],
        [ 25,  30,  35,  40,  45],
        [ 50,  55,  60,  65,  70],
        [ 75,  80,  85,  90,  95],
        [100, 105, 110, 115, 120],
        [125, 130, 135, 140, 145],
        [150, 155, 160, 165, 170]],

       [[175, 180, 185, 190, 195],
        [200, 205, 210, 215, 220],
        [225, 230, 235, 240, 245],
        [250, 255, 260, 265, 270],
        [275, 280, 285, 290, 295],
        [300, 305, 310, 315, 320],
        [325, 330, 335, 340, 345]]])

In [13]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [14]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))

In [22]:
np.inner(left_mat, right_mat)

ValueError: shapes (2,3) and (3,5) not aligned: 3 (dim 1) != 5 (dim 1)

In [31]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

<h2>Operations along axes</h2>

In [47]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [48]:
# shape
my_3D_array.shape

(2, 7, 5)

In [15]:
my_3D_array.sum()

2415

In [34]:
(69 * 70)/2

2415.0

In [16]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [36]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [37]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [17]:
my_3D_array.sum(axis=3)

ValueError: 'axis' entry is out of bounds

<h2>Broadcasting Rules</h2>

In [18]:
my_2D_array = np.ones(35, dtype='int_').reshape((7,5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [19]:
my_random_2D_array = np.random.random((7,5))

In [20]:
my_random_2D_array

array([[ 0.26793672,  0.63481459,  0.18127565,  0.20660408,  0.03063249],
       [ 0.82146174,  0.40632404,  0.21725374,  0.34243475,  0.50811982],
       [ 0.22060927,  0.01814938,  0.59028788,  0.15990405,  0.02283588],
       [ 0.2294825 ,  0.29849942,  0.15109631,  0.7930673 ,  0.07420171],
       [ 0.96306589,  0.32355314,  0.06878512,  0.17037222,  0.98652378],
       [ 0.08526596,  0.45865241,  0.76108488,  0.82086342,  0.56867181],
       [ 0.60932465,  0.06248052,  0.67190184,  0.6745738 ,  0.81260319]])

In [21]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[  0.    ,   0.6348,   0.3626,   0.6198,   0.1225],
        [  4.1073,   2.4379,   1.5208,   2.7395,   4.5731],
        [  2.2061,   0.1996,   7.0835,   2.0788,   0.3197],
        [  3.4422,   4.776 ,   2.5686,  14.2752,   1.4098],
        [ 19.2613,   6.7946,   1.5133,   3.9186,  23.6766],
        [  2.1316,  11.925 ,  20.5493,  22.9842,  16.4915],
        [ 18.2797,   1.9369,  21.5009,  22.2609,  27.6285]],

       [[  9.3778,  22.8533,   6.7072,   7.851 ,   1.1947],
        [ 32.8585,  16.6593,   9.1247,  14.7247,  22.3573],
        [  9.9274,   0.8349,  27.7435,   7.6754,   1.119 ],
        [ 11.4741,  15.2235,   7.857 ,  42.0326,   4.0069],
        [ 52.9686,  18.119 ,   3.9208,   9.8816,  58.2049],
        [  5.116 ,  27.9778,  47.1873,  51.7144,  36.395 ],
        [ 39.6061,   4.1237,  45.0174,  45.871 ,  56.0696]]])

In [23]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [64]:
my_3D_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [24]:
my_3D_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [65]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)